apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: {{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
