namespace: kafka

replicaCount: 1

onlyInstallServices: false

image:
  repository: guilindev/kafka-producer
  tag: latest
  pullPolicy: IfNotPresent

zookeeper:
  image:
    repository: bitnami/zookeeper
    tag: latest

kafka:
  image:
    repository: bitnami/kafka
    tag: latest

producer:
  image:
    repository: guilindev/kafka-producer
    tag: latest

consumer:
  image:
    repository: guilindev/kafka-consumer
    tag: latest

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

podAnnotations: {}
podLabels: {}

securityContext: {}
podSecurityContext: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 3

nodeSelector: {}
affinity: {}
tolerations: []

volumeMounts: []
volumes: []

imagePullSecrets: []
serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []
